on: [pull_request, push]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cargo fmt
      run: cargo fmt --all -- --check
   
  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cargo clippy
      run: cargo clippy --all --all-targets -- -D warnings
  
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cargo test
      run: cargo test
